#ifndef BOARD_DATA_H
#define BOARD_DATA_H

#include "board.h"

static const uint8_t BOARD[BOARD_HEIGHT][BOARD_WIDTH] = {
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID},
    {WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID},
    {WALL_ID,POWER_DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,POWER_DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID},
    {WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,WALL_ID,HOME_DOOR_ID,HOME_DOOR_ID,WALL_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,DOT_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,DOT_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,EMPTY_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID},
    {WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID},
    {WALL_ID,POWER_DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,EMPTY_ID,EMPTY_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,POWER_DOT_ID,WALL_ID},
    {WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID},
    {WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID},
    {WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,DOT_ID,WALL_ID},
    {WALL_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,DOT_ID,WALL_ID},
    {WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID,WALL_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
    {EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID,EMPTY_ID},
};

#endif // !BOARD_DATA_H
